startupers/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from main.feed import LatestNewsFeed

urlpatterns = [
    # Examples:
    url(r'^$', 'main.views.home', name='home'),
    url(r'^rss/$', LatestNewsFeed(), name='rss_feed'),
    url(r'^portfolio/$', 'main.views.portfolio', name='portfolio'),
    url(r'^portfolio/(?P<slug>[^\.]+).html', 'main.views.view_portfolio', name='view_portfolio'),
    url(r'^blog/$', 'main.views.blog', name='view_blog'),
    url(r'^about/$', 'main.views.about', name='about'),
    url(r'^contacts/$', 'main.views.contacts', name='contacts'),
    url(r'^faq/$', 'main.views.faq_page', name='faq'),
    url(r'^services/$', 'main.views.services', name='services'),
    url(r'^thanks/$', 'main.views.thanks', name='thanks'),
    url(r'^ajax_subscribe/$', 'main.views.ajax_subscribe'),
    url(r'^blog/(?P<category_slug>[^\.]+)/(?P<post_slug>[^\.]+).html', 'main.views.view_post', name='view_post'),
    url(r'^blog/(?P<category_slug>[^\.]+)/$', 'main.views.view_blog_category', name='view_blog_category'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^ckeditor/', include('ckeditor.urls')),

    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
# -*- coding: utf-8 -*-

from django.db import models
from sorl.thumbnail import ImageField
from sorl.thumbnail import get_thumbnail
from django.contrib.auth.models import User
from django.conf import settings
from ckeditor.fields import RichTextField
# Create your models here.


class MenuItem(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    weight = models.IntegerField(unique=True)

    class Meta:
        verbose_name = "Menu item"
        verbose_name_plural = "Menu items"


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Post(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category)
    content = RichTextField()
    annotation = models.CharField(max_length=255, blank=True)
    image = ImageField(upload_to='uploads/news/')
    author = models.ForeignKey(User)
    published = models.BooleanField(default=True)
    slug = models.SlugField(unique=True)
    date = models.DateTimeField()

    def __unicode__(self):
        return self.title

    def preview(self):
        if self.image:
            im = get_thumbnail(self.image, '100x100', crop='center')
            return '<img src="%s">' % im.url
        return ''

    preview.allow_tags = True

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    @models.permalink
    def get_absolute_url(self):
        return ('view_post', (), {
            'category_slug': self.category.slug,
            'post_slug': self.slug,
        })


class PortfolioCategory(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "Portfolio category"
        verbose_name_plural = "Portfolio categories"


class Portfolio(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(PortfolioCategory)
    content = RichTextField()
    image = ImageField(upload_to='uploads/portfolio/', blank=True, null=True)
    url = models.URLField(blank=True)
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    def preview(self):
        if self.image:
            im = get_thumbnail(self.image, '100x100', crop='center')
            return '<img src="%s">' % im.url
        return ''

    preview.allow_tags = True

    class Meta:
        verbose_name = "Portfolio item"
        verbose_name_plural = "Portfolio items"

    @models.permalink
    def get_absolute_url(self):
        return ('view_portfolio', (), {
            'slug': self.slug,
        })


class PortfolioImage(models.Model):
    image = ImageField(upload_to='uploads/portfolio/images/')
    title = models.CharField(max_length=255, blank=True)
    portfolio = models.ForeignKey(Portfolio)


class StaticPage(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField()
    slug = models.SlugField(unique=True)
    template = models.FilePathField(path=settings.TEMPLATES_MAIN_DIR+'/static/')

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "Static page"
        verbose_name_plural = "Static pages"


class Testimonials(models.Model):
    message = RichTextField()
    author = models.CharField(max_length=255)
    date = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return self.message

    class Meta:
        verbose_name = "Testimonial"
        verbose_name_plural = "Testimonials"


class Team(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    image = ImageField(upload_to='uploads/team/')
    about = RichTextField(blank=True)
    facebook_url = models.URLField(blank=True)
    twitter_url = models.URLField(blank=True)

    class Meta:
        verbose_name = "Team"
        verbose_name_plural = "Team"

    def preview(self):
        if self.image:
            im = get_thumbnail(self.image, '100x100', crop='center')
            return '<img src="%s">' % im.url
        return ''

    preview.allow_tags = True


class FAQ(models.Model):
    question = models.CharField(max_length=255)
    answer = RichTextField()
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "FAQ"
        verbose_name_plural = "FAQ"


class Subscriber(models.Model):
    email = models.EmailField(max_length=75, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Subscriber"
        verbose_name_plural = "Subscribers"


class Feedback(models.Model):
    name = models.CharField(max_length=255, blank=True)
    email = models.EmailField(max_length=75)
    phone = models.CharField(max_length=40, blank=True)
    subject = models.CharField(max_length=255, blank=True)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Feedback"
        verbose_name_plural = "Feedback"

templates/about.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}{% trans "About" %}{% endblock %}
{% block pagetitle %}
    <!--page Title-->
    <div id="page-title">
        <div class="title-box">
            <div class="container">
                <h2 class="icon-size animated fadeInUp"><i class="glyphicon glyphicon-user"></i>
                    {% trans "About Us" %}
                </h2>
                <ul class="breadcrumb pull-right">
                    <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
                    <li class="active">{% trans "About Us" %}</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section class="middle">
        <div class="container">
            <div class="row">

                <!-- Start content-block column-->
                <div class="col-sm-12 col-md-9 ">
                    <div class="content-block">
                        <div class="headline">
                            <h1>{% trans "About Us" %}</h1>
                        </div>
                        <p>
                            <img src="{% static "img/large-img-01.jpg" %}" alt="{% trans "About us" %}"
                                 class="img-responsive"/>
                        </p>

                        <p>
Startupreneurs AB is the Swedish company, working in the EU countries with innovative and startup projects as IT partner and solution provider - software development and telecom
                        </p>

                        <p>
We build the strong relationship with our partners and customers to guarantee the long-term lifecycle and success of the products 
                        </p>


                        <div class="headline">
                            <h2>{% trans "Our History" %}</h2>
                        </div>
                        <p>
                            Startupreneurs AB was founded by two IT and management experts that know each other from the university times but met years after to create the new sophisticated team
                        </p>

                        <hr/>
        

                        <div class="row our-team">
                            <div class="headline text-center">
                                <h2>{% trans "Meet Our Team" %}</h2>
                            </div>
                            <p class="text-center">Come and say hi to us :)
                            </p>

                            {% for person in team %}
                                <div class="col-sm-6 col-md-4">
                                    <div class="team-thumbnail">
                                        <div class="team-thumbnail-img">
                                            {% thumbnail person.image "320x250" crop="center" as im %}
                                                <img src="{{ im.url }}" alt="{{ person.title }}">
                                            {% endthumbnail %}
                                        </div>
                                        <div class="caption text-center">
                                            <h4>{{ person.first_name }} {{ person.last_name }}, {{ person.position }}</h4>

                                            <p>{{ person.about|safe }}</p>
                                        </div>
                                        {% if person.facebook_url or person.twitter_url %}
                                        <div class="social-btn theme-color">
                                            {% if person.facebook_url %}
                                                <a href="{{ person.facebook_url }}" target="_blank"
                                                   class="btn btn-md btn-carouselwhite icon-circle"><i
                                                        class="fa fa-facebook"></i></a>
                                            {% endif %}
                                            {% if person.twitter_url %}
                                                <a href="{{ person.twitter_url }}" target="_blank"
                                                   class="btn btn-md btn-carouselwhite icon-circle"><i
                                                        class="fa fa-twitter"></i></a>
                                            {% endif %}

                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}


                        </div>
                        <!-- End .our-team-->
                    </div>
                    <!-- End .content-block-->
                </div>
                <!-- End content-block column-->

                {% include "sidebar.html" %}


            </div>
            <!-- End .row-->
        </div>
        <!-- End .container-->
    </section>  <!-- End .middle-->

{% endblock %}

templates/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Startup Entrepreneurs is the team of the company Startupreneurs AB from Sweden, experts in IT startups">
    <meta name="author" content="Startupreneurs AB">
    <link rel="shortcut icon" href="favicon.png">

    <title>{% block title %}{% endblock %} | Startup Entrepreneurs</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">

    <!-- Custom Color Theme for this template -->
    <link href="{% static "css/theme-cadet_blue.css" %}" rel="stylesheet">

    <!-- font awesome icons -->
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">

    <!-- Banner Animation -->
    <link rel="stylesheet" href="{% static "css/animate-custom.css" %}">

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>

    <!-- Toaster -->
    <link href="{% static "css/toastr.min.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static "js/html5shiv.js" %}"></script>
      <script src="{% static "js/respond.min.js" %}"></script>
    <![endif]-->
</head>

<body>

{% include "header.html" %}
{% block pagetitle %}{% endblock %}
{% block carousel %} {% endblock %}


<div class="content-wrapper {% block extra-content-style %}{% endblock %}">
    {% block content %}{% endblock %}

    {% include "footer.html" %}

</div>
<!-- /.content-wrapper -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    window.jQuery || document.write('<script src="{% static "js/jquery.min.js" %}"><\/script>')
</script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/toastr.min.js" %}"></script>


{% block extra-js-bottom %}{% endblock %}

<script src="{% static "js/custom.js" %}"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40816910-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}{% trans "Contacts" %}{% endblock %}
{% block pagetitle %}
    <!--page Title-->
    <div id="page-title">
        <div class="title-box">
            <div class="container">
                <h2 class="icon-size animated fadeInUp"><i class="glyphicon glyphicon-earphone"> </i>
                    {% trans "Contact page" %}</h2>
                <ul class="breadcrumb pull-right">
                    <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
                    <li class="active">{% trans "Contacts" %}</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section class="middle">
        <!-- starts: Google Maps -->
        <div class="gmapfixed_block">
            <div id="googlemaps-container-top"></div>
            <div id="googlemaps" class="google-map google-map-full"></div>
            <div id="googlemaps-container-bottom"></div>
        </div>
        <!-- end: Google Maps -->
        <div class="container">
            <div class="row">
                <!-- Start content-block column-->
                <div class="content-block">
                    <div class="col-md-7 contactform">
                        <div class="headline">
                            <h2>{% trans "GET IN TOUCH" %}</h2>
                        </div>
                        <p>
                            Please initiate a dialog with us by letting us know about your business, we are here to help
                        </p>
                        {% if form.errors %}{{ form.name.errors }}{% endif %}
                        <form class="form-light" role="form" method="post" action="">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>{% trans "Name" %}</label>
                                <input type="text" class="form-control" placeholder="John Smith"
                                       id="id_name" name="name" {% if form.name.value %} value="{{ form.name.value }}" {% endif %}/>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>{% trans "Email" %}</label>
                                        <input type="email" class="form-control" placeholder="your@email.com"
                                               id="id_email" name="email" {% if form.email.value %} value="{{ form.email.value }}" {% endif %}>
                                        {% if form.email.errors %}
                                            <div class="form-error">{{ form.email.errors }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <label>{% trans "Phone" %}</label>
                                        <input type="text" class="form-control" placeholder="+(XX)-(XXX)-XXX-XX-XX"
                                               id="id_phone" name="phone" {% if form.phone.value %} value="{{ form.phone.value }}" {% endif %}>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>{% trans "Subject" %}</label>
                                <input type="text" class="form-control" id="subject"
                                       placeholder="Subject" id="id_subject" name="subject" {% if form.subject.value %} value="{{ form.subject.value }}" {% endif %}>
                            </div>
                            <div class="form-group">
                                <label>{% trans "Message" %}</label>
                                <textarea class="form-control" placeholder="Write you message here..."
                                          style="height:100px;" id="id_message" name="message">{% if form.message.value %} {{ form.message.value }} {% endif %}</textarea>
                                {% if form.message.errors %}
                                    <div class="form-error">{{ form.message.errors }}</div>
                                {% endif %}
                            </div>
                            <button type="submit" class="btn btn-theme">
                                {% trans "Send message" %}</button>
                        </form>
                    </div>
                    <!-- End .contactform-->

                    <div class="col-md-5 address-block">
                        <div class="headline">
                            <h2>{% trans "Contacts" %}</h2>
                        </div>
                        <p>
                            Cup of coffee together in our premises or any other comfortable place is a good start of the partnership
                        </p>
                        <h4>Head Office</h4>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-map-marker"></i> Location: Stockholm, Sweden</li>
                            <li><i class="fa fa-phone"></i> Phone: +46 73 984-3221</li>
                            <li><i class="fa fa-envelope"></i> Email: <a
                                    href="mailto:info@ad-says.com">info@startupreneurs.se</a></li>
                        </ul>

                        <h4>Technical office</h4>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-map-marker"></i> Location: Kyiv, Ukraine</li>
                            <li><i class="fa fa-phone"></i> Phone: +38 096 385-8213</li>
                            <li><i class="fa fa-envelope"></i> Email: <a
                                    href="mailto:info@ad-says.com">info@startupreneurs.se</a></li>
                        </ul>
                    </div>
                    <!-- End .address-block-->

                </div>
                <!-- End .content-block-->
            </div>
            <!-- End .row-->
        </div>
        <!-- End .container-->
    </section>  <!-- End .middle-->
{% endblock %}

{% block extra-js-bottom %}
    <!--  js For Google map  -->
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>


    <script src="{% static "js/plugins/jquery.gmap.min.js" %}"></script>
    <script type="text/javascript">
        /* for Google map */

        $(window).load(function () {
            LoadGmaps();
        });

        /* Add Your Company Name latitude and  longitude here.
         * for latitude and longitude please check http://itouchmap.com/latlong.html
         *  */
        var latitude = "59.3420754";
        var longitude = "18.0648189";
        var details = "Startup Entrepreneurs";

        function LoadGmaps() {
            var myLatlng = new google.maps.LatLng(latitude, longitude);
            var myOptions = {
                zoom: 16,
                scrollwheel: true,
                center: myLatlng,
                navigationControl: true,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            var map = new google.maps.Map(document.getElementById("googlemaps"), myOptions);
            var marker = new google.maps.Marker({
                position: myLatlng,
                map: map,
                icon: '{% static "img/map_icon.png" %}'
            });
            var infowindow = new google.maps.InfoWindow({
                content: details
            });
            google.maps.event.addListener(marker, "click", function () {
                infowindow.open(map, marker);
            });
            infowindow.open(map, marker);

        }

    </script>

{% endblock %}

</body>
</html>

templates/footer.html
{% load i18n %}
<footer class="main-footer">
			<div class="container">
			  	<div class="row">
			  			 <a href="#" class="top-btn theme-color"> <i class="fa fa-angle-up"></i></a>	
							<div class="col-sm-12 col-md-3 about-widget widget">
								<h4>{% trans "About Us" %}</h4>
								<p>We are Startup Entrepreneurs, IT experts with responsibility and knowledge how to make things happen.</p>
								<p>We create innovations from scratch, we touch and fix broken projects and inspire for future!</p>
							</div>
							
							<div class="col-sm-12 col-md-3 gallery-flickr widget">
								<h4>Flickr Photostream</h4>
								<div class="flickr-widget clearfix">
										<script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?count=6&amp;display=latest&amp;size=s&amp;layout=x&amp;source=user&amp;user=15817260@N02"></script>                            
			                           <!-- "15817260@N02"  replace this with your flickr ID--> 
									<div class="clearfix"></div>
								</div>
							</div>
							
							<div class="col-sm-6 col-md-3 widget">
								<div class="address">
									<h4>{% trans "Get in Touch With us" %}</h4>
									<address>
										<strong>Our locations</strong><br>
										Stockholm, Sweden<br>
										Kyiv, Ukraine<br>
									</address>
									<address>
										<i class="glyphicon glyphicon-earphone"></i> +46 73 984-3221<br>
										<a href="mailto:#" class="no-flip"><i class="glyphicon glyphicon-envelope"></i> info@startupreneurs.se</a>
									</address>
								</div>
								<div class="social-icons">
							 	 	<ul class="list-unstyled list-inline">
										<li><a href="https://www.facebook.com/pages/Startup-Entrepreneurs/622580134430955" class="fa fa-facebook"></a></li>
										<li><a href="#" class="fa fa-twitter"></a></li>
										<li><a href="#" class="fa fa-google-plus"></a></li>
										<li><a href="#" class="fa fa-linkedin"></a></li>
										<li><a href="#" class="fa fa-pinterest"></a></li> 
									</ul>
							 	 </div> <!-- / Social icons -->  
							</div>
							<div class="col-sm-6 col-md-3 subscribe widget">
								<h4>{% trans "Subscribe Now" %}</h4>
								<p>Please subscribe to get more of our updates directly to your email</p>
								<form role="form" id="sub-form">
                                    {% csrf_token %}
			                    	<input type="email" class="form-control" id="id_email" name="email" placeholder="Your E-Mail" required> <br />
			                    	<button type="submit" class="btn btn-default btn-sm" id="sub_button">{% trans "Subscribe" %}</button>
		                		</form>
							</div>
						</div><!-- /.row -->  
			</div> <!-- /.container --> 
			
			<div class="copyright-link"> 
					<p class="text-center"> 
			           <!-- Copyright information. You can replace your site link here --> 
			            &copy; 2013-{% now 'Y' %}<a href="{% url "home" %}"> Startup Entrepreneurs</a> {% trans "All Rights Reserved." %}
		            </p> 
			</div> 
		</footer> <!-- /.main-footer -->

templates/project-details.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load thumbnail %}
{% block title %}{{ item.title }}{% endblock %}
{% block pagetitle %}


    <!--page Title-->
    <div id="page-title">
        <div class="title-box">
            <div class="container">
                <h2 class="icon-size animated fadeInUp"><i class="fa fa-globe"> </i> {% trans "Projects Details" %}</h2>
                <ul class="breadcrumb pull-right">
                    <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
                    <li><a href="{% url "portfolio" %}">{% trans "Portfolio" %}</a></li>
                    <li class="active">{{ item.title }}</li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

{% block content %}
    <section class="middle">
        <div class="container">
            <div class="row">
                <!-- Start content-block column-->
                <div class="content-block">
                    <div class="col-md-7">
                        <div id="projectCarousel" class="carousel slide">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                {% for image in item.portfolioimage_set.all %}
                                    <li data-target="#projectCarousel" data-slide-to="{{ forloop.counter }}"
                                        {% if forloop.first %}class="active"{% endif %}></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner">
                                {% for image in item.portfolioimage_set.all %}
                                    <div class="item{% if forloop.first %} active{% endif %}">
                                        {% thumbnail image.image "900x700" crop="center" as im %}
                                            <img src="{{ im.url }}" alt="{{ image.title }}">
                                        {% endthumbnail %}
                                        <div class="container">
                                            <div class="carousel-caption">
                                                <p>{{ image.title }}</p>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#projectCarousel" data-slide="prev"><span
                                    class="glyphicon glyphicon-chevron-left"></span></a>
                            <a class="right carousel-control" href="#projectCarousel" data-slide="next"><span
                                    class="glyphicon glyphicon-chevron-right"></span></a>
                        </div>
                        <!-- /.carousel -->
                    </div>
                    <div class="col-md-5">
                        <div class="headline">
                            <h1>{{ item.title }}</h1>
                        </div>
                        <p>
                            {{ item.content|safe }}
                        </p>
                        {% if item.url %}
                            <a href="{{ item.url }}" class="btn btn-theme" target="_blank">{{ item.url }}</a>
                        {% endif %}
                    </div>
                </div>
                <!-- End .content-block-->
            </div>
            <!-- End .row-->
        </div>
        <!-- End .container-->
    </section>  <!-- End .middle-->


{% endblock %}
		


templates/sidebar.html
{% load i18n %}
<!-- Start  sidebar Column-->
<div class="col-sm-12 col-md-3 ">
    <section class="sidebar right-sidebar">
        <aside class="widget">
            <div class="headline">
                <h2>{% trans "Search" %}</h2>
            </div>
            <form role="form">
                <div class="input-group">
                    <label class="sr-only" for="search-field">{% trans "Search" %}</label>
                    <input type="search" class="form-control placeholder" id="search-field"
                           placeholder="Search">
						                <span class="input-group-btn">
						                <button class="btn btn-default" type="button">{% trans "Go!" %}</button>
						                </span></div>
            </form>
        </aside>

        <aside class="widget">
            <div class="headline">
                <h2>{% trans "Categories" %}</h2>
            </div>
            <!-- Add ".no-flip" class to "a" tag or "ul" tag to remove flip effect  -->
            <ul class="ul-list list-unstyled categories-list">
                {% for category in categories %}
                    <li><i class="fa fa-chevron-right"></i> <a
                            href="{% url "view_blog_category" category.slug %}">{{ category.title }}</a></li>
                {% endfor %}
            </ul>
        </aside>
    </section>
    <!-- End section.sidebar-->
</div>
<!-- End  sidebar Column-->